name: Update README with Info
description: Update the README with cool information
on: push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: can i get a heya
        run: |
          touch .env
          echo GH_PERSONAL_TOKEN=${{secrets.GH_PERSONAL_TOKEN}} >> .env
          echo LASTFM_API_KEY=${{secrets.LASTFM_API_KEY}} >> .env
          node index.js