on: [push]

jobs:
  update_readme:
    runs-on: ubuntu-latest
    name: Update README with Info
    steps:
      - name: insert .env
        run: |
          touch .env
          echo GH_PERSONAL_TOKEN=${{secrets.GH_PERSONAL_TOKEN}} >> .env
          echo LASTFM_API_KEY=${{secrets.LASTFM_API_KEY}} >> .env

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
        node-version: '14'
      - run: npm install
      
      - run: node ./index.js