on: [push]

jobs:
  update_readme:
    runs-on: ubuntu-latest
    name: Update README with Info
    steps:
      - name: can i get a heya
        run: |
          touch .env
          echo GH_PERSONAL_TOKEN=${{secrets.GH_PERSONAL_TOKEN}} >> .env
          echo LASTFM_API_KEY=${{secrets.LASTFM_API_KEY}} >> .env
          node index.js